<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Pre_sessional_4</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Pre_sessional_4_files/libs/clipboard/clipboard.min.js"></script>
<script src="Pre_sessional_4_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Pre_sessional_4_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Pre_sessional_4_files/libs/quarto-html/popper.min.js"></script>
<script src="Pre_sessional_4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Pre_sessional_4_files/libs/quarto-html/anchor.min.js"></script>
<link href="Pre_sessional_4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Pre_sessional_4_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Pre_sessional_4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Pre_sessional_4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Pre_sessional_4_files/libs/bootstrap/bootstrap-215b371544c282197b31c8aa00ce3677.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pre_sessional_4</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<p>This document was built using Quarto. Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
<p>Below is a snippit of R code that is executed when the document is created.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>You can copy these code snippits into your own RStudio to begin to build you own analyses. As you go through the document create a new R script in RStudio and add the code section one after another. By then of this each section you will have built an analysis pipeline for each type of design. You can then use this as a basis for future analyses.</p>
</section>
<section id="one-way-anova-between" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova-between">ONE-WAY ANOVA (BETWEEN)</h2>
<p>The first data set we are going to work with, is from a study that looked at the level of conspiracy beliefs (scored from a questionnaire) and the political ideology of the 30 participants which was categorised into 3 levels based on the party they voted for in the last election.</p>
<p>Before we load the data what is a good practice to do to our <strong>R</strong> Environment? What is the code to do this?</p>
<textarea rows="2" cols="60" placeholder="Type your answer here..."></textarea>
<div class="callout callout-style-default callout-note callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Clear it of variables that might be left over from a previous analysis. rm(list = ls()) Make sure to include this code in your analysis script as it will be executed invisibly in this document.</p>
</div>
</div>
</div>
<p>Following the pattern seen in previous tutorials we will load the .csv file and check some basic things about it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/vrNeuro/R_Teaching_Materials/refs/heads/main/Presessional/PoliticalData.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df) <span class="co">#display the top 6 rows</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  political_group conspiracy_beliefs
1               1                 72
2               1                 64
3               1                 74
4               1                 66
5               1                 59
6               1                 63</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> political_group conspiracy_beliefs
 Min.   :1       Min.   :45.00     
 1st Qu.:1       1st Qu.:57.25     
 Median :2       Median :63.00     
 Mean   :2       Mean   :66.63     
 3rd Qu.:3       3rd Qu.:77.75     
 Max.   :3       Max.   :91.00     
 NA's   :71      NA's   :71        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(df,class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   political_group conspiracy_beliefs 
         "integer"          "numeric" </code></pre>
</div>
</div>
<p>The first thing to notice is that currently <code>df$political_group</code> is stored as <strong>integer</strong> data, this means it is made up of whole numbers. As we have done previously we need to tell <strong>R</strong> that this is categorical data, but this time we are also going to give these levels of the categorical variable labels. The way the current numbers map onto the labels for the levels is: 1 - left<br>
2 - centre<br>
3 - right<br>
</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#change the political group to a factor with the correct labels</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>political_group <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>political_group,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"centre"</span>, <span class="st">"right"</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#check that it has been properly configured using</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>political_group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  left centre  right   NA's 
    10     10     10     71 </code></pre>
</div>
</div>
<p>So something looks right, we have correctly changed the <code>df$political_group</code> to a factor and the labels appear when we ask for a summary. However, there are 71 <strong>NA</strong>, this is what <strong>R</strong> uses to represent missing data. This suggests that we have a lot of rows of our dataframe that contain these NA values for some reason in the <code>political_group</code> column.</p>
<p>Let’s try and see if we can understand what might have happened. We can use the function <strong>is.na()</strong> to find the location of all of these <code>NA</code> values, this will return TRUE whenever that bit of data is NA and FALSE when it is anything else. In <em>tutorial 3</em> we saw how we could use these LOGICAL values to select rows from a dataframe, we can do the same here to get the content of all rows in which <code>df$political_group</code> is NA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">is.na</span>(df<span class="sc">$</span>political_group),]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    political_group conspiracy_beliefs
31             &lt;NA&gt;                 NA
32             &lt;NA&gt;                 NA
33             &lt;NA&gt;                 NA
34             &lt;NA&gt;                 NA
35             &lt;NA&gt;                 NA
36             &lt;NA&gt;                 NA
37             &lt;NA&gt;                 NA
38             &lt;NA&gt;                 NA
39             &lt;NA&gt;                 NA
40             &lt;NA&gt;                 NA
41             &lt;NA&gt;                 NA
42             &lt;NA&gt;                 NA
43             &lt;NA&gt;                 NA
44             &lt;NA&gt;                 NA
45             &lt;NA&gt;                 NA
46             &lt;NA&gt;                 NA
47             &lt;NA&gt;                 NA
48             &lt;NA&gt;                 NA
49             &lt;NA&gt;                 NA
50             &lt;NA&gt;                 NA
51             &lt;NA&gt;                 NA
52             &lt;NA&gt;                 NA
53             &lt;NA&gt;                 NA
54             &lt;NA&gt;                 NA
55             &lt;NA&gt;                 NA
56             &lt;NA&gt;                 NA
57             &lt;NA&gt;                 NA
58             &lt;NA&gt;                 NA
59             &lt;NA&gt;                 NA
60             &lt;NA&gt;                 NA
61             &lt;NA&gt;                 NA
62             &lt;NA&gt;                 NA
63             &lt;NA&gt;                 NA
64             &lt;NA&gt;                 NA
65             &lt;NA&gt;                 NA
66             &lt;NA&gt;                 NA
67             &lt;NA&gt;                 NA
68             &lt;NA&gt;                 NA
69             &lt;NA&gt;                 NA
70             &lt;NA&gt;                 NA
71             &lt;NA&gt;                 NA
72             &lt;NA&gt;                 NA
73             &lt;NA&gt;                 NA
74             &lt;NA&gt;                 NA
75             &lt;NA&gt;                 NA
76             &lt;NA&gt;                 NA
77             &lt;NA&gt;                 NA
78             &lt;NA&gt;                 NA
79             &lt;NA&gt;                 NA
80             &lt;NA&gt;                 NA
81             &lt;NA&gt;                 NA
82             &lt;NA&gt;                 NA
83             &lt;NA&gt;                 NA
84             &lt;NA&gt;                 NA
85             &lt;NA&gt;                 NA
86             &lt;NA&gt;                 NA
87             &lt;NA&gt;                 NA
88             &lt;NA&gt;                 NA
89             &lt;NA&gt;                 NA
90             &lt;NA&gt;                 NA
91             &lt;NA&gt;                 NA
92             &lt;NA&gt;                 NA
93             &lt;NA&gt;                 NA
94             &lt;NA&gt;                 NA
95             &lt;NA&gt;                 NA
96             &lt;NA&gt;                 NA
97             &lt;NA&gt;                 NA
98             &lt;NA&gt;                 NA
99             &lt;NA&gt;                 NA
100            &lt;NA&gt;                 NA
101            &lt;NA&gt;                 NA</code></pre>
</div>
</div>
<p>From this we can see that all the value in the <code>df$conspiracy_beliefs</code> is also NA for these rows so they just seem to be completely missing data. Therefore we want to remove these rows of data completely from our data set. There are multiple ways of doing this in <strong>R</strong>, for example <code>df &lt;- na.omit(df)</code> would remove any row in which a NA appeared in <strong>any</strong> column. This can be useful for removing rows when you have multiple columns that NAs can appear in. However, here we are going to do something slightly different. Previously we have used the <code>==</code> operator to test if something is equivalent to something else. The opposite of this is <code>x != y</code>, this which returns TRUE if <code>x</code> does not equal <code>y</code>.</p>
<p>Therefore this code tell <strong>R</strong> to overwrite the dataframe <code>df</code> with the data from <code>df</code>, in rows only where <code>df$political_group</code> is not NA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df[<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>political_group), ] </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>political_group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  left centre  right 
    10     10     10 </code></pre>
</div>
</div>
<p>We can now see from the summary that we only have the 30 rows of ‘good’ data left in <code>df</code>.</p>
<p>Our research hypothesis is that a participants political group will affect their level belief in conspiracy theories. We have data with one categorical <strong>independent variable</strong> or <strong>IV</strong>, with three levels, and we have data with one <strong>dependent variable</strong> or <strong>DV</strong> which is continuous data. Our data is also <strong>independent</strong> with each participant appearing only once. So the analysis we want to conduct is a <strong>one-way ANOVA</strong>, in this case a 1x3 ANOVA, since we have three levels to our IV.</p>
<p>The easiest way to perform ANOVAs (and more complex analyses like regressions) in <strong>R</strong> is to use formula objects. What is the symbol we use in a formula in <strong>R</strong> to separate the DVs from the IVs, and to which side of this symbol do we place our DVs?</p>
<textarea rows="2" cols="60" placeholder="Type your answer here..."></textarea>
<div class="callout callout-style-default callout-note callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We use the tilde symbol ~ The DVs go on the left of this and the IVs on the right</p>
</div>
</div>
</div>
<p>The full name of an ANOVA is <strong>AN</strong>anlysis <strong>O</strong>f <strong>VA</strong>riance, and in <strong>R</strong> the function to perform this analysis is called <strong>aov()</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>polFormula <span class="ot">&lt;-</span> conspiracy_beliefs <span class="sc">~</span> political_group <span class="co">#define the formula</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>anovaMdl <span class="ot">&lt;-</span> <span class="fu">aov</span>(polFormula, <span class="at">data =</span> df) <span class="co">#perform the ANOVA and assign the results to a variable</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>anovaMdl <span class="co">#print the contents of the model to the screen</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
   aov(formula = polFormula, data = df)

Terms:
                political_group Residuals
Sum of Squares         3774.067   928.900
Deg. of Freedom               2        27

Residual standard error: 5.865467
Estimated effects may be unbalanced</code></pre>
</div>
</div>
<p>We can see that the <code>anovaMdl</code> object printed some useful results to screen but we can improve on this and get more information by using the <code>summary()</code> function to print a summary of it for us. We have previously used this function to summarise the contents of a dataframe but it can also be used to summarise the contents of other objects such as the outputs of statistics functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anovaMdl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
political_group  2   3774  1887.0   54.85 3.09e-10 ***
Residuals       27    929    34.4                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This table now contains all of the information we would need to report this statistical test in a paper or report. Similarly to when we looked at the output of the t-tests, it is a question of learning where we get the different bits of information from in the output.</p>
<p>A one-way ANOVA revealed a significant effect of political group on conspiracy beliefs, <em>F</em>(2, 27) = 54.85, <em>p</em> &lt; .001.</p>
<p>However, we are not finished yet. The ANOVA results tell us that there is a statistically significant effect of political_group on conspiracy_beliefs but not which groups actually differ from each other. For this we need to conduct <strong>post-hoc</strong> tests, which compare each group against the others in pairs. They also apply correction for <strong>multiple-comparisons</strong>. The most commonly use post-hoc comparison test in psychology is <strong>Tukey’s Honest Significant Difference</strong> method, and is inculded in base <strong>R</strong> with the function <strong>TukeyHSD()</strong>. As we can see below it takes the output of the <code>aov()</code> function as its input, it then outputs a table of the pairwise comparisons. Below we are also creating a boxplot using the formula we defined earlier.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(polFormula, df, <span class="at">xlab =</span> <span class="st">"Political Group"</span>, <span class="at">ylab =</span> <span class="st">"Conspiracy Beliefs"</span>, <span class="at">main =</span> <span class="st">"Boxplot Displaying how Conspiracy Beliefs Vary by Golitical Group"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pre_sessional_4_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anovaMdl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = polFormula, data = df)

$political_group
             diff      lwr       upr     p adj
centre-left  -9.1 -15.6038 -2.596198 0.0048702
right-left   17.9  11.3962 24.403802 0.0000007
right-centre 27.0  20.4962 33.503802 0.0000000</code></pre>
</div>
</div>
<p>Here the left column of each row of the table is the comparison performed, for example the first is comparing the centre to the left group. The diff column is the difference in means, here is is negative as centre is less than left as can be seen in the boxplot and the sum is performed <em>centre-left</em>. The final column is the adjusted p value for this test (after correction for multiple comparisons) and we can see it is significant.</p>
<p>It is always a good idea to check that your statistics make sense given a plot of your data, and when reporting them make clear which <strong>direction</strong> the effects are in, not just if they were signficant or not.</p>
<p>So we would add this information to our earlier write up of the overall ANOVA results to give a full report:</p>
<p>A one-way ANOVA revealed a significant effect of political group on conspiracy beliefs, <em>F</em>(2, 27) = 54.85, <em>p</em> &lt; .001. Post hoc comparisons using the Tukey HSD test indicated that conspiracy beliefs were significantly lower in the centre group than in the left group (<em>Mdiff</em> = −9.10, <em>p</em> = .005). Conspiracy beliefs were significantly higher in the right group than in the left group (<em>Mdiff</em> = 17.90, <em>p</em> &lt; .001), and significantly higher in the right group than in the centre group (<em>Mdiff</em> = 27.00, <em>p</em> &lt; .001). All three pairwise comparisons were therefore statistically significant, indicating that each political group differed significantly from the other two on conspiracy beliefs.</p>
</section>
<section id="one-way-anova-within" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova-within">ONE-WAY ANOVA (WITHIN)</h2>
<p>The data we will look at for the next section will be from an experiment that investigated the performance of participants on three different spatial memory tasks, with each participant completing all three tasks. The experiment also recorded whether the participants were regular usersof virtual reality devices as well as the number of hours they spent each week playing computer games.</p>
<p>As usual we will clear the Environment of variables and load the csv file:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/vrNeuro/R_Teaching_Materials/refs/heads/main/Presessional/VRTaskData.csv"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df) <span class="co">#display the top 6 rows</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  VRuse gameHours    Task1    Task2    Task3
1     2         5 57.00772 42.83350 51.07771
2     1         7 57.10089 23.26025 49.66249
3     2         5 60.10248 21.32076 23.30864
4     1        10 20.33102 43.21899 33.03326
5     1         7 55.13143 35.33398 34.54462
6     2         0 20.92061 12.97497 40.82358</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     VRuse         gameHours          Task1           Task2      
 Min.   :1.000   Min.   : 0.000   Min.   :20.33   Min.   :12.97  
 1st Qu.:1.000   1st Qu.: 4.000   1st Qu.:40.54   1st Qu.:29.45  
 Median :1.000   Median : 7.500   Median :54.96   Median :40.04  
 Mean   :1.375   Mean   : 7.275   Mean   :51.21   Mean   :40.52  
 3rd Qu.:2.000   3rd Qu.:11.000   3rd Qu.:60.80   3rd Qu.:51.32  
 Max.   :2.000   Max.   :15.000   Max.   :77.75   Max.   :71.57  
     Task3      
 Min.   :16.08  
 1st Qu.:34.39  
 Median :45.79  
 Mean   :45.26  
 3rd Qu.:55.50  
 Max.   :76.67  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(df,class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    VRuse gameHours     Task1     Task2     Task3 
"integer" "integer" "numeric" "numeric" "numeric" </code></pre>
</div>
</div>
<p>As before we will need to properly code the <code>df$VRuse</code> variable as a categorical variable, in this case it is coded so that a 1 indicates that they did not use VR regularly and a 2 if they did</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>VRuse <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>VRuse, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This data set contains two separate IVs, the first is the within subject IV of task (with 3 levels), the second is the between subject IV of VRuse (with two levels). Each participant took part in all three tasks but is only a member of one of the levels of the between subject IV.</p>
<p>For now we are going to concentrate on just the within subject IV of task. As we saw in <em>tutorial 1</em>, we sometimes need to reshape our data in order for it to be in the right format for <strong>R</strong> to analyse. Although in many statistical packages such as SPSS and Jamovi we tend to organise our data with one row per participant, many functions in <strong>R</strong> require one row per <strong>observation</strong>. Just as before we are going to use the <strong>tidyr</strong> package and it’s useful pivot functions to accomplish this. Before we reshape the table we are also going to add a new variable to it called <code>Subject</code>, this is because we need some way to track which bits of data belong to which subject when performing the ANOVA. This ‘Subject’ code will simply be based on the row number in df.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Subject <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(df))) <span class="co"># add the row number as a new factor variable</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df) <span class="co">#first check the dimensions of our current dataframe</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40  6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr) <span class="co">#load the package</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#create a long format table</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>dfLong <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(df, <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"Task"</span>), <span class="at">names_to =</span> <span class="st">"Task"</span>, <span class="at">values_to =</span> <span class="st">"Score"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dfLong) <span class="co">#check the dimensions of our new long dataframe</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 120   5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dfLong)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  VRuse gameHours Subject Task  Score
  &lt;fct&gt;     &lt;int&gt; &lt;fct&gt;   &lt;chr&gt; &lt;dbl&gt;
1 Yes           5 1       Task1  57.0
2 Yes           5 1       Task2  42.8
3 Yes           5 1       Task3  51.1
4 No            7 2       Task1  57.1
5 No            7 2       Task2  23.3
6 No            7 2       Task3  49.7</code></pre>
</div>
</div>
<p>We can see that we started with 40 rows of 6 variables (including our new Subject variable). The new <code>dfLong</code> is 120 rows of 5 variables. It has taken the 3 columns that started with the name ‘Task’ and created a new variable called <code>dfLong$Task</code> that indicates which column the <code>df$Score</code> came from. It has left out <code>gameHours</code> variable intact, but since each participant now has three rows the same value is repeated three times.</p>
<p>The last thing we need to do is to recode our new <code>dfLong$Task</code> variable as a factor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>dfLong<span class="sc">$</span>Task <span class="ot">&lt;-</span> <span class="fu">factor</span>(dfLong<span class="sc">$</span>Task, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Task1"</span>, <span class="st">"Task2"</span>, <span class="st">"Task3"</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dfLong) <span class="co">#check it has worked</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  VRuse gameHours Subject Task  Score
  &lt;fct&gt;     &lt;int&gt; &lt;fct&gt;   &lt;fct&gt; &lt;dbl&gt;
1 Yes           5 1       Task1  57.0
2 Yes           5 1       Task2  42.8
3 Yes           5 1       Task3  51.1
4 No            7 2       Task1  57.1
5 No            7 2       Task2  23.3
6 No            7 2       Task3  49.7</code></pre>
</div>
</div>
<p>We are now ready to perform our 1-way repeated measures ANOVA. This is very similar to how we performed the one-way between subjects ANOVA. However, we need to specify the <strong>error term</strong> so that the within subjects factor is accounted for. We will discuss this more during the main statistics course.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run the within-subjects (repeated measures) one-way ANOVA</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>rmAnova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Score <span class="sc">~</span> Task <span class="sc">+</span> <span class="fu">Error</span>(Subject<span class="sc">/</span>Task), <span class="at">data =</span> dfLong)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rmAnova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Subject
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 39  10366   265.8               

Error: Subject:Task
          Df Sum Sq Mean Sq F value  Pr(&gt;F)   
Task       2   2296  1147.9   5.623 0.00523 **
Residuals 78  15922   204.1                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>To report and interpret these results we would look at the table below the “Error: Subject:Task” line. We could write this up as:</p>
<p>A one-way repeated measures ANOVA showed that task significantly affected performance scores, <em>F</em>(2, 78) = 5.62, <em>p</em> = .005.</p>
<p>As with the between subjects ANOVA we want to perform post-hoc comparisons to see where the difference lies. Happily <strong>R</strong> has a function exactly for this that will also apply adjustments for multiple comparisons, here I have selected a <strong>bonferroni</strong> correction but other methods can be selected using the function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(dfLong<span class="sc">$</span>Score, dfLong<span class="sc">$</span>Task, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using paired t tests 

data:  dfLong$Score and dfLong$Task 

      Task1  Task2 
Task2 0.0088 -     
Task3 0.3592 0.1378

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>This demonstrates that only Task1 and Task2 were significantly difference after a bonferroni correction for multiple comparisions with <em>p</em> = 0.009. We can find <em>p</em> value for the Task1 - Task3 comparison in the bottom left of the grid (<em>p</em> = 0.359), and Task2 - Task3 <em>p</em> = 0.138.</p>
<p>To create a boxplot to visualise this we can either do this from the long format data in <code>dfLong</code> or the original wide format data in <code>df</code>. The code below shows the version from the original <code>df</code> format as it is slightly simpler:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df[, <span class="fu">c</span>(<span class="st">"Task1"</span>, <span class="st">"Task2"</span>, <span class="st">"Task3"</span>)],</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"VR Task Performance"</span>, <span class="at">ylab =</span> <span class="st">"Score"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">boxwex =</span> <span class="fl">0.4</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># connect each subject's three scores with a line</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)) {</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">y =</span> <span class="fu">as.numeric</span>(df[i, <span class="fu">c</span>(<span class="st">"Task1"</span>, <span class="st">"Task2"</span>, <span class="st">"Task3"</span>)]),</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.2</span>))</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co"># overlay the individual points on top of the lines</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(df)), df<span class="sc">$</span>Task1, <span class="at">pch =</span> <span class="dv">16</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">2</span>, <span class="fu">nrow</span>(df)), df<span class="sc">$</span>Task2, <span class="at">pch =</span> <span class="dv">16</span>)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">rep</span>(<span class="dv">3</span>, <span class="fu">nrow</span>(df)), df<span class="sc">$</span>Task3, <span class="at">pch =</span> <span class="dv">16</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pre_sessional_4_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To complete a statistical report we should also include some descriptive statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df[,<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Task1           Task2           Task3      
 Min.   :20.33   Min.   :12.97   Min.   :16.08  
 1st Qu.:40.54   1st Qu.:29.45   1st Qu.:34.39  
 Median :54.96   Median :40.04   Median :45.79  
 Mean   :51.21   Mean   :40.52   Mean   :45.26  
 3rd Qu.:60.80   3rd Qu.:51.32   3rd Qu.:55.50  
 Max.   :77.75   Max.   :71.57   Max.   :76.67  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(df[,<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>],sd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Task1    Task2    Task3 
14.83106 15.39747 14.73167 </code></pre>
</div>
</div>
<p>A full writeup of these results would be something like this:</p>
<p>A one-way repeated measures ANOVA was conducted to examine the effect of task on performance scores. Descriptive statistics showed that mean scores were highest for Task 1 (<em>M</em> = 51.21, <em>SD</em> = 14.83), followed by Task 3 (<em>M</em> = 45.26, <em>SD</em> = 14.73) and Task 2 (<em>M</em> = 40.52, <em>SD</em> = 15.40). The effect of task was statistically significant (<em>F</em>(2, 78) = 5.62, <em>p</em> = .005). Post hoc pairwise comparisons using paired-samples t-tests with Bonferroni correction indicated that scores were significantly higher on Task 1 than on Task 2 (p = .009). Neither the comparison between Task 1 and Task 3 (p = .359) nor between Task 2 and Task 3 (p = .138) reached statistical significance.</p>
</section>
<section id="mixed-two-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="mixed-two-way-anova">MIXED TWO-WAY ANOVA</h2>
<p>Finally we will use a new data set to look at a mixed ANOVA, now we will also include the between subjects factor of <code>VRuse</code>. We will continue with the same data set as the previous section so no need to clear the Environment. However, if you are starting from this section make sure to include the code that loads the initial data.</p>
<p>The code to perform this is very similar to our one-way within subjects ANOVA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mixedAnova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Score <span class="sc">~</span> VRuse <span class="sc">*</span> Task <span class="sc">+</span> <span class="fu">Error</span>(Subject<span class="sc">/</span>Task), <span class="at">data =</span> dfLong)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mixedAnova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Subject
          Df Sum Sq Mean Sq F value   Pr(&gt;F)    
VRuse      1   3420    3420   18.71 0.000106 ***
Residuals 38   6947     183                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Subject:Task
           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Task        2   2296  1147.9   6.822 0.001884 ** 
VRuse:Task  2   3135  1567.3   9.315 0.000241 ***
Residuals  76  12788   168.3                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We have switched <code>Task</code> on the right side of the <code>~</code> to <code>VRuse * Task</code>, this is a shorthand way of asking <strong>R</strong> to calculate the <strong>main effect</strong> of <code>VRuse</code>, <code>Task</code>, and also their <strong>interaction</strong> term <code>VRuse:Task</code>. We could have used this formula <code>Score ~ VRuse + Task + VRuse:Task + Error(Subject/Task)</code> and produced identical results but the <code>*</code> shorthand is very useful to prevent a long list.</p>
<p>The output table above now has two additional lines: 1 - in the Error: Subject table we can now see a line for the main effect of VRuse 2 - in the Error: Subject:Task we now see an additional line for the interaction effect</p>
<p>Here is how we would write this up for a report or paper:</p>
<p>A 2 (VRuse) × 3 (Task) mixed ANOVA was conducted, with VRuse as a between-subjects factor and Task as a within-subjects factor. There was a significant main effect of VRuse, <em>F</em>(1, 38) = 18.71, <em>p</em> &lt; .001, indicating that overall performance scores differed between VR-use groups. There was also a significant main effect of Task, <em>F</em>(2, 76) = 6.82, <em>p</em> = .002. There was also a significant VRuse × Task interaction, <em>F</em>(2, 76) = 9.32, <em>p</em> &lt; .001, indicating that the effect of task on performance differed depending on VR-use group.</p>
<p>We can also produce a boxplot of this data to match the statistical test we have performed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Score <span class="sc">~</span> VRuse <span class="sc">*</span> Task, <span class="at">data =</span> dfLong,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"salmon"</span>),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Task"</span>, <span class="at">ylab =</span> <span class="st">"Score"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"VR Task Performance by VR Use Group"</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="fl">4.5</span>, <span class="fl">7.5</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Task1"</span>, <span class="st">"Task2"</span>, <span class="st">"Task3"</span>))</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">levels</span>(dfLong<span class="sc">$</span>VRuse), <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"salmon"</span>),</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"VRuse"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pre_sessional_4_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot helps us see where our results come from: 1 - Main effect of VRuse: the Yes group is on average lower than the No across the three tasks 2 - Main effect of task: as before Task2 seems to be lower than task1 if averaged across both VR groups 3 - Interaction effect: the No group are relatively similar across the three tasks, but the No group show a change in performance across the tasks.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>