<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Pre_sessional_5 – PG Stats Intro</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="worksheet.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PG Stats Intro</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Pre_sessional_0.html"> 
<span class="menu-text">Unit 0</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#quarto" id="toc-quarto" class="nav-link active" data-scroll-target="#quarto">Quarto</a></li>
  <li><a href="#correlations" id="toc-correlations" class="nav-link" data-scroll-target="#correlations">CORRELATIONS</a></li>
  <li><a href="#linear-regression-with-a-single-predictor" id="toc-linear-regression-with-a-single-predictor" class="nav-link" data-scroll-target="#linear-regression-with-a-single-predictor">LINEAR REGRESSION WITH A SINGLE PREDICTOR</a></li>
  <li><a href="#linear-regression-with-a-multiple-predictors" id="toc-linear-regression-with-a-multiple-predictors" class="nav-link" data-scroll-target="#linear-regression-with-a-multiple-predictors">LINEAR REGRESSION WITH A MULTIPLE PREDICTORS</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pre_sessional_5</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<p>This document was built using Quarto. Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
<p>Below is a snippit of R code that is executed when the document is created.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>You can copy these code snippits into your own RStudio to begin to build you own analyses. As you go through the document create a new R script in RStudio and add the code section one after another. By then of this each section you will have built an analysis pipeline for each type of design. You can then use this as a basis for future analyses.</p>
</section>
<section id="correlations" class="level2">
<h2 class="anchored" data-anchor-id="correlations">CORRELATIONS</h2>
<p>In the data set we will use for this tutorial (it is an imaginary study). the data comes from a study of the correlates of trust in traditional journalism in a sample drawn from the general population. Participants provided demographic information (age, gender) and completed a battery of questionnaires that measured the following variables: &nbsp; - trust in traditional journalism (TTJ; higher scores reflect greater trust in traditional journalism outlets [e.g.,newspapers]); &nbsp; - social media use (SMU; average number of hours per day spent on social media platforms such as Facebook, Instagram, Twitter, TikTok, etc.); &nbsp; - reliance on traditional vs.&nbsp;social media for news (RTN; relative reliance [%] on traditional media sources relative to social media platforms for news; higher scores reflect greater reliance on traditional media); &nbsp; - endorsement of conspiracy theories (ECT; higher scores reflect greater belief in a range of conspiracy theories); &nbsp; - political conservatism (PC; higher scores reflect greater conservatism); &nbsp; - mistrust of experts (ME; higher scores reflect greater mistrust of experts [medical professionals, scientists, economists, legal scholars, etc.]). &nbsp;</p>
<p>We will use our familiar code pattern to clear the Environment and load the data from the csv file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/SocialMediaData.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df) <span class="co">#display the top 6 rows</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age gender      smu      rsm      ect        pc
1  64      0 24.82422 41.01882 17.81689 15.273564
2  81      0 17.58041 45.31633 14.52861 18.015221
3  67      0 30.89202 46.21940 17.36508  9.807414
4  63      0 12.49083 42.54467 17.59220 18.120238
5  54      1 24.02393 41.56892 12.16890  3.710834
6  58      1  9.79409 45.16734 17.66462 23.201985</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            gender         smu               rsm       
 Min.   :32.00   Min.   :0.0   Min.   : 0.0256   Min.   :33.45  
 1st Qu.:51.00   1st Qu.:0.0   1st Qu.:12.5160   1st Qu.:42.36  
 Median :59.00   Median :0.5   Median :17.6306   Median :45.35  
 Mean   :58.96   Mean   :0.5   Mean   :17.9376   Mean   :45.49  
 3rd Qu.:66.00   3rd Qu.:1.0   3rd Qu.:23.9875   3rd Qu.:48.79  
 Max.   :90.00   Max.   :1.0   Max.   :44.1446   Max.   :55.06  
      ect              pc        
 Min.   :12.17   Min.   : 1.486  
 1st Qu.:16.06   1st Qu.:14.088  
 Median :17.35   Median :19.337  
 Mean   :17.43   Mean   :19.087  
 3rd Qu.:18.93   3rd Qu.:24.214  
 Max.   :23.78   Max.   :42.592  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(df,class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age    gender       smu       rsm       ect        pc 
"integer" "integer" "numeric" "numeric" "numeric" "numeric" </code></pre>
</div>
</div>
<p>Here the only variable that we need to change into a factor is <code>df$gender</code>. This is coded a 0 for male and 1 for female (this is purely for statistical simplicity in the tutorial and is not making any claims about the number of genders).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>gender,<span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"M"</span>,<span class="st">"F"</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>gender) <span class="co">#check the change as worked.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> M  F 
75 75 </code></pre>
</div>
</div>
<p>All of our other variables of interest are continuous variables and therefore to examine the relationship between them we will use <strong>correlations</strong>.</p>
<p>The first thing we want to do is to check the degree of correlation between variables. In <strong>R</strong> the function to perform correlations is <strong>cor.test()</strong>. If we wanted to look at the help for this function to understand how it works what would we type into the console:</p>
<textarea rows="2" cols="60" placeholder="Type your answer here..."></textarea>
<div class="callout callout-style-default callout-note callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>?cor.test or help(cor.test)</p>
</div>
</div>
</div>
<p>If we wanted to examine the correlation between social media use (smu) and political conservatism (pc) we would use:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>smu,df<span class="sc">$</span>pc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  df$smu and df$pc
t = -2.1365, df = 148, p-value = 0.03428
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.32424730 -0.01307521
sample estimates:
       cor 
-0.1729743 </code></pre>
</div>
</div>
<p>Here is how we would write this up in a report:</p>
<p>A Pearson correlation was conducted to examine the relationship between social media use (smu) and PC scores. There was a statistically significant, weak negative correlation between the two variables, <em>r</em>(148) = −.17, <em>p</em> = .034.</p>
<p>Try to spot where the numbers in the report come from in the output, as with t-tests and ANOVAs everything we need is present, it is just a matter of getting the information from the right places. Also notice that the direction of the correlation being <strong>negative</strong> is reported as well as its size, this is vital information to include.</p>
<p>A common way of depicting the relationship between two continuous variables is with a scatter plot, to do this we will use the <strong>plot()</strong> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>smu,df<span class="sc">$</span>pc,<span class="at">xlab =</span> <span class="st">"Social Media Use"</span>, <span class="at">ylab =</span> <span class="st">"Political Conservtism"</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">main =</span> <span class="st">"Scatter Plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pre_sessional_5_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To better visualise the pattern of the relationship we can add a best fit line using the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df<span class="sc">$</span>smu,df<span class="sc">$</span>pc,<span class="at">xlab =</span> <span class="st">"Social Media Use"</span>, <span class="at">ylab =</span> <span class="st">"Political Conservtism"</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">main =</span> <span class="st">"Scatter Plot"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pc <span class="sc">~</span> smu, <span class="at">data =</span> df) <span class="co">#create a linear model</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="co">#plot the linear model as a straight line</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pre_sessional_5_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This shows the weak negative relationship that the statistics indicated, as scores on Social Media Use increase, Political Conservatism decreases. The function <strong>abline()</strong> allows us to draw straight lines on plots. The input argument we gave to <code>abline()</code> to create this straight line relationship was a linear model created by the <strong>lm()</strong> function, we will come back to this later when we look at how to perform regressions.</p>
<p>Often we want to examine the correlations between all of our variables at one time, instead of checking this pair by pair we can use <strong>cor()</strong> to check all of our numeric variables at one time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"smu"</span>, <span class="st">"rsm"</span>, <span class="st">"ect"</span>, <span class="st">"pc"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             age         smu         rsm          ect          pc
age  1.000000000 -0.46552533 -0.15281053 -0.001234091  0.32043604
smu -0.465525326  1.00000000  0.16967350 -0.016880581 -0.17297427
rsm -0.152810525  0.16967350  1.00000000  0.303801652  0.02200696
ect -0.001234091 -0.01688058  0.30380165  1.000000000  0.04570774
pc   0.320436045 -0.17297427  0.02200696  0.045707738  1.00000000</code></pre>
</div>
</div>
<p>You’ll notice that here we used <code>cor()</code> instead of <code>cor.test()</code>, <code>cor()</code> does not perform a statistical test of significance (we don’t get <em>p</em> values), instead it outputs a <strong>correlation matrix</strong> of the pearson R coefficients.</p>
<p>The first thing to notice about this matrix is that on the diagonal from top-left to bottom-right are all 1s. This is because each cell in the matrix holds the pearson R coefficient for the correlation between the variable named in the row and the one in the column. Those on the diagonal are therefore the correlation of a variable and itself, which by definition is 1.</p>
<p>The other thing to notice is that the matrix is symmetrical around this diagonal, so the value of -0.0012 in the 4th row, 1st column, is the same as that in the 1st row, 4th column. This is because the correlation of <code>ect ~ age</code> is identical to that of <code>age ~ ect</code>, the order we specify the variables in a correlation does not matter.</p>
<p>It is usually good practice to also visually inspect your data, and we can produce a scatterplot matrix using the <strong>pairs()</strong> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(df[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"smu"</span>, <span class="st">"rsm"</span>, <span class="st">"ect"</span>, <span class="st">"pc"</span>)],</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">"Scatterplot Matrix"</span>, <span class="at">pch =</span> <span class="dv">16</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Pre_sessional_5_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="linear-regression-with-a-single-predictor" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-with-a-single-predictor">LINEAR REGRESSION WITH A SINGLE PREDICTOR</h2>
<p>Earlier to create a straight line of best fit to add to our correlation plot we used the function <strong>lm()</strong>. This is also the function we can use to compute more complex regressions later on. However, for now it is useful as an illustration.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pc <span class="sc">~</span> smu, <span class="at">data =</span> df)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pc ~ smu, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.6636  -5.3971   0.3076   5.4721  22.3335 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 22.06704    1.52829  14.439   &lt;2e-16 ***
smu         -0.16615    0.07777  -2.137   0.0343 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.646 on 148 degrees of freedom
Multiple R-squared:  0.02992,   Adjusted R-squared:  0.02337 
F-statistic: 4.565 on 1 and 148 DF,  p-value: 0.03428</code></pre>
</div>
</div>
<p>The formula <code>pc ~ smu</code> reads as “pc predicted by smu” — same left-side-outcome, right-side-predictor convention you’ve used in <code>aov()</code> and other places throughout these tutorials. Also, as you have seen previously <code>summary()</code> gives you the full output of these models. In the case of regression we get: &nbsp; the intercept and slope estimates, &nbsp; their standard errors, &nbsp; t-values and p-values, &nbsp; plus R², &nbsp; and the overall model F-test.</p>
<p>Interestingly if we compare this output to the output of the correlation we performed earlier we will observe some patterns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>corModel <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df<span class="sc">$</span>smu,df<span class="sc">$</span>pc)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>corModel</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  df$smu and df$pc
t = -2.1365, df = 148, p-value = 0.03428
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.32424730 -0.01307521
sample estimates:
       cor 
-0.1729743 </code></pre>
</div>
</div>
<p>The first is that the <em>p</em> value for the correlation is identical to that of the overall model F-test at the bottom of the regression output. &nbsp; The second is that the degrees of freedom in the correlation and the F test also match. &nbsp; The last is harder to spot but if you take the <em>r</em> value from a correlation and square it, you get the <em>R<sup>2</sup></em> value of the regression:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>corModel<span class="sc">$</span>estimate<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      cor 
0.0299201 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0299201</code></pre>
</div>
</div>
<p>Performing a regression with a single predictor is identical to performing a pearsons correlation. In fact regression, ANOVAs, t-tests and correlations are all part of a larger framework of statistics called the <strong>general linear model</strong> or <strong>GLM</strong>.</p>
<p>For example, if we take our <code>df$gender</code> variable that has two levels and perform a regression with this as the only predictor:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(pc <span class="sc">~</span> gender, <span class="at">data =</span> df)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pc ~ gender, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.5445  -5.1554   0.3239   4.6394  24.7923 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  20.3733     0.8838  23.051   &lt;2e-16 ***
genderF      -2.5732     1.2499  -2.059   0.0413 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.654 on 148 degrees of freedom
Multiple R-squared:  0.02784,   Adjusted R-squared:  0.02127 
F-statistic: 4.238 on 1 and 148 DF,  p-value: 0.04128</code></pre>
</div>
</div>
<p>We can compare this output to a t-test of the same model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>tModel <span class="ot">&lt;-</span> <span class="fu">t.test</span>(pc <span class="sc">~</span> gender, <span class="at">data =</span> df, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>tModel</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  pc by gender
t = 2.0587, df = 148, p-value = 0.04128
alternative hypothesis: true difference in means between group M and group F is not equal to 0
95 percent confidence interval:
 0.1031889 5.0432964
sample estimates:
mean in group M mean in group F 
       20.37329        17.80005 </code></pre>
</div>
</div>
<p>Again we see that the <em>p</em> value of the t-test matches that of the <em>F</em> test of the regression, &nbsp; The degrees of freedom match &nbsp; If we square the <em>t</em> value from the t-test we get the <em>F</em> value of the regression test</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>tModel<span class="sc">$</span>statistic<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       t 
4.238151 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>fstatistic[<span class="dv">1</span>] </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
4.238151 </code></pre>
</div>
</div>
</section>
<section id="linear-regression-with-a-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-with-a-multiple-predictors">LINEAR REGRESSION WITH A MULTIPLE PREDICTORS</h2>
<p>If we want to examine the effect of multiple predictors at the same time on an outcome variable we simply need to add these to the right hand side of the formula. For example this formula specifies that we want to look at how the predictors, smu, age, and ect all act to predict pc.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>formula2 <span class="ot">&lt;-</span> pc <span class="sc">~</span> smu <span class="sc">+</span> age <span class="sc">+</span> ect</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can then pass this and the data to the <code>lm()</code> function and use <code>summary()</code> to get a useful output of the linear regression model</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula2,df)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = formula2, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.5812  -5.6706   0.5909   4.8313  18.8873 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.33842    6.93011   0.482 0.630721    
smu         -0.02821    0.08497  -0.332 0.740327    
age          0.22701    0.06544   3.469 0.000687 ***
ect          0.16464    0.28273   0.582 0.561241    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.392 on 146 degrees of freedom
Multiple R-squared:  0.1055,    Adjusted R-squared:  0.0871 
F-statistic: 5.739 on 3 and 146 DF,  p-value: 0.0009706</code></pre>
</div>
</div>
<p>We get a very similar output to before, we still get an overall <em>F</em> test of the significance of the whole model. However, the table has now expanded and contains a row for each of our three predictors. The <strong>Estimate</strong> column contains the <strong>b</strong> coefficient (unstandardised) of the relationship of that predictor to the outcome (whilst holding the other predictors constant). The final column <code>Pr(&gt;|t|)</code> gives the <em>p</em> value of the significance of that particular predictor.</p>
<p>Based on this table, which predictors have a significant association with the outcome variable when they are all included in the model.</p>
<textarea rows="2" cols="60" placeholder="Type your answer here..."></textarea>
<div class="callout callout-style-default callout-note callout-titled" title="Show answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Only age seems to have a significant relationship with <em>p</em> &lt; 0.0001. The <em>p</em> values for the other two predictors are &gt;0.05.</p>
</div>
</div>
</div>
<p>To report the results of this regression in APA style we would write something like this:</p>
<p>A multiple linear regression was conducted to examine whether social media use (smu), age, and endorsement of conspiracy theories (ect) predicted political conservatism (pc). The overall model was statistically significant, <em>F</em>(3, 146) = 5.74, <em>p</em> &lt; .001, and explained approximately 11% of the variance in political conservatism (<em>R<sup>2</sup></em> = .11, adjusted <em>R<sup>2</sup></em> = .09).</p>
<p>Age was a significant positive predictor of political conservatism, <em>b</em> = 0.23, <em>SE</em> = 0.07, <em>t</em>(146) = 3.47, <em>p</em> &lt; .001, such that older participants tended to score higher on conservatism. Neither social media use (<em>b</em> = −0.03, <em>SE</em> = 0.08, <em>t</em>(146) = −0.33, <em>p</em> = .740) nor ect (<em>b</em> = 0.16, <em>SE</em> = 0.28, <em>t</em>(146) = 0.58, <em>p</em> = .561) significantly predicted political conservatism once the other variables in the model were accounted for.</p>
<p>Quick reference for how the values map:</p>
<p><em>F</em>(3, 146) — from the model’s 3 and 146 DF &nbsp; <em>p</em> &lt; .001 — from p-value: 0.0009706 &nbsp; <em>R<sup>2</sup></em> = .11, adjusted <em>R<sup>2</sup></em> = .09 — from Multiple R-squared: 0.1055 and Adjusted R-squared: 0.0871 &nbsp;</p>
<p>For each predictor, <em>b</em> = Estimate, <em>SE</em> = Std. Error, <em>t</em>(146) = t value (residual df = 146 for all three), and <em>p</em> = Pr(&gt;|t|), rounded to three decimals or reported as &lt; .001 where applicable.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>