<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PS71020_Unit2_Homework – PG Stats Intro</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="worksheet.css">
<link rel="stylesheet" href="answer-gate.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PG Stats Intro</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Pre_sessional_0.html"> 
<span class="menu-text">Unit 0</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#section-a.-the-data-set" id="toc-section-a.-the-data-set" class="nav-link active" data-scroll-target="#section-a.-the-data-set">SECTION A. THE DATA SET</a></li>
  <li><a href="#section-b.-missing-data" id="toc-section-b.-missing-data" class="nav-link" data-scroll-target="#section-b.-missing-data">SECTION B. MISSING DATA</a></li>
  <li><a href="#section-c.-detecting-outliers-with-z-scores" id="toc-section-c.-detecting-outliers-with-z-scores" class="nav-link" data-scroll-target="#section-c.-detecting-outliers-with-z-scores">SECTION C. DETECTING OUTLIERS WITH Z-SCORES</a></li>
  <li><a href="#sec-compound-plots" id="toc-sec-compound-plots" class="nav-link" data-scroll-target="#sec-compound-plots">SECTION D. COMPOUND PLOTS</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PS71020_Unit2_Homework</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Some general notes about the weekly homeworks
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Each week will have an associated homework worksheet in a similar format to this. You should go through the worksheet during your own time to get extra practice. Try to answer the worksheet questions in your own words however. Model answers will be available within the document itself but please try to answer the questions properly before revealing them. A full R script for the analysis will be published VLE page from Fridays after the labs so you can compare your own script. If your question relates specifically to the lecture content or the homework sheets, please contact Peter Holland by email or use the forum on the VLE page.</em></p>
</div>
</div>
<p>Homework Learning Outcomes: &nbsp;</p>
<p>1 - Use RStudio to screen data for missing values &nbsp;</p>
<p>2 - Use RStudio to exclude cases with missing values &nbsp;</p>
<p>3 - Use RStudio to perform mean imputation &nbsp;</p>
<p>4 - Use z-scores to detect outliers &nbsp;</p>
<p>5 - Use ggplot2 and extensions to create compound plots &nbsp;</p>
<section id="section-a.-the-data-set" class="level2">
<h2 class="anchored" data-anchor-id="section-a.-the-data-set">SECTION A. THE DATA SET</h2>
<p>The dataset for the homework this week is adapted from one of the datasets used as an example in the corresponding lecture. A sample of 191 university students resident in Dubai were measured on their impulsivity-related personality traits, their use of conventional cigarettes and their use of a nicotine-based local product called dokha. The questionnaires include an impulsivity measure called the UPPS-P, and a measure of behavioural approach and inhibition, the BIS/BAS scales. The researchers were planning to examine the extent to which the personality variables predict smoking behaviour, and to examine how these relationships might be moderated by socio-demographic factors. Prior to the focal analyses planned for the dataset, the dataset needs to be screened and cleaned.</p>
<p>As usual we will load the data set using the <code>read.csv()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"lec_dokha_example_data_withoutliers.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The first thing we will do is to check for missing data in the data set.</p>
<p><strong>What code does R use for missing data?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>NA</p>
</div>
</div>
</section>
<section id="section-b.-missing-data" class="level2">
<h2 class="anchored" data-anchor-id="section-b.-missing-data">SECTION B. MISSING DATA</h2>
<p><strong>What is one function we can use to summarise a data set and find the number of missing values in each variable? It produces the output shown below</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>summary(), in this case we would use <code>summary(df)</code>.</p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     Gender           Age          Education     MaritalStatus  
 Min.   :1.000   Min.   :18.00   Min.   :1.000   Min.   :1.000  
 1st Qu.:1.000   1st Qu.:19.00   1st Qu.:1.000   1st Qu.:1.000  
 Median :1.000   Median :22.00   Median :1.000   Median :1.000  
 Mean   :1.471   Mean   :22.51   Mean   :1.723   Mean   :1.099  
 3rd Qu.:2.000   3rd Qu.:25.50   3rd Qu.:2.000   3rd Qu.:1.000  
 Max.   :2.000   Max.   :30.00   Max.   :6.000   Max.   :4.000  
                                                                
  EthnicOrigin      Religion         Income          Dokha1      
 Min.   :1.000   Min.   :1.000   Min.   :0.000   Min.   :0.0000  
 1st Qu.:1.000   1st Qu.:1.000   1st Qu.:0.000   1st Qu.:0.0000  
 Median :1.000   Median :2.000   Median :1.000   Median :1.0000  
 Mean   :2.712   Mean   :2.445   Mean   :1.743   Mean   :0.5812  
 3rd Qu.:4.000   3rd Qu.:2.000   3rd Qu.:4.000   3rd Qu.:1.0000  
 Max.   :9.000   Max.   :6.000   Max.   :5.000   Max.   :1.0000  
                                                                 
  dokha_total2  Fagerstrom_total Negative_UrgencyUPPS Lack_of_PremediationUPPS
 Min.   :0.00   Min.   : 0.00    Min.   : 13.00       Min.   :11.00           
 1st Qu.:0.00   1st Qu.: 0.00    1st Qu.: 25.25       1st Qu.:17.00           
 Median :0.00   Median : 0.00    Median : 32.00       Median :22.00           
 Mean   :2.67   Mean   : 1.89    Mean   : 35.12       Mean   :21.66           
 3rd Qu.:6.00   3rd Qu.: 3.00    3rd Qu.: 38.00       3rd Qu.:25.00           
 Max.   :8.00   Max.   :10.00    Max.   :444.00       Max.   :50.00           
                                 NAs    :1            NAs    :1               
 Lack_of_PerseveranceUPPS Sensation_SeekingUPPS Positive_UrgencyUPPS
 Min.   :10.00            Min.   :17.00         Min.   :14.00       
 1st Qu.:16.00            1st Qu.:32.00         1st Qu.:26.25       
 Median :20.00            Median :37.00         Median :31.00       
 Mean   :19.91            Mean   :37.01         Mean   :32.13       
 3rd Qu.:23.00            3rd Qu.:43.75         3rd Qu.:39.00       
 Max.   :31.00            Max.   :48.00         Max.   :56.00       
 NAs    :1                NAs    :1             NAs    :1           
     DRIVE            FUN              RR             BAS             BIS      
 Min.   : 6.00   Min.   : 4.00   Min.   :12.00   Min.   :23.00   Min.   : 7.0  
 1st Qu.:11.00   1st Qu.:11.00   1st Qu.:16.00   1st Qu.:39.00   1st Qu.:17.0  
 Median :12.00   Median :13.00   Median :18.00   Median :44.00   Median :20.0  
 Mean   :12.31   Mean   :12.64   Mean   :17.87   Mean   :42.82   Mean   :20.2  
 3rd Qu.:14.00   3rd Qu.:15.00   3rd Qu.:20.00   3rd Qu.:47.00   3rd Qu.:24.0  
 Max.   :16.00   Max.   :16.00   Max.   :20.00   Max.   :52.00   Max.   :28.0  
 NAs    :2       NAs    :2       NAs    :2       NAs    :2       NAs    :2     </code></pre>
</div>
</div>
<p><strong>What is the extent of missing data in the dataset?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>We seem to have some missing values, with 4 variables missing one value and 5 missing two values. However, at this stage it isn’t clear if these are across multiple participants or only two participants who are missing multiple data points.</p>
</div>
</div>
<p><strong>R</strong> contains several useful functions for finding missing data. The simplest is we can find the location of <code>NA</code>s in a single variable, using the function <code>is.na()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(df<span class="sc">$</span>DRIVE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[145] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[157] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[169] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[181] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
</div>
<p>However, this list of <code>TRUE</code> or <code>FALSE</code> values (<strong>logical</strong> values), is not the most reader friendly for identifying their position. We can use a second function called <code>which()</code> that tells us the positions of any true values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">is.na</span>(df<span class="sc">$</span>DRIVE))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   9 186</code></pre>
</div>
</div>
<p>This not tells us positions 9 and 186 of the <code>df$DRIVE</code> variables are <code>NA</code>s, this corresponds to rows 9 and 186 of <code>df</code>.</p>
<p>A way to check for complete cases of data (rows with no <code>NA</code> values), we can use a function called <code>complete.cases()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">complete.cases</span>(df))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]   1   2   3   4   5   6   7   8  10  11  12  13  14  15  16  17  18  19
 [19]  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
 [37]  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
 [55]  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
 [73]  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
 [91]  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
[109] 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
[127] 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
[145] 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
[163] 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
[181] 182 183 184 185 187 188 189 190 191</code></pre>
</div>
</div>
<p>If we look carefully through the list of the row numbers of the complete cases we can see that 9 and 186 are missing. So it seems like we have two participants that account for all of our missing data.</p>
<p>It would make it easier for us to change the code to return the row numbers of participants that are <strong>not</strong> complete cases. We can do this by adding a single character to our previous code. <strong>What is it? Also write the line of code that would create the following output</strong> For a hint see <a href="./PS71020_Unit2_Lab.html#sec-univariate-screening">Section B</a>.</p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>The <code>!</code> flips <code>TRUE</code> and <code>FALSE</code> values to become the opposite. Importantly it leaves <code>NA</code> values as <code>NA</code>. The code would be: <code>which(!complete.cases(df))</code></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1]   9 186</code></pre>
</div>
</div>
<p><strong>Given the scale of missing data what do you think would be a good option for handling it in this case?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>Given the size of the dataset here and the extent of missing data, it is unlikely that any solution we undertake will have a major effect on the study results. The simplest option would be to remove the cases, or we could impute the values.</p>
</div>
</div>
<p>We have seen in the Lab <a href="./PS71020_Unit2_Lab.html#sec-univariate-screening">Section B</a> how to use <code>subset()</code> to select only certain data.</p>
<p><strong>What code would we need to create a new data set called <code>dfClean</code> with only the complete cases included?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p><code>dfClean &lt;- subset(df,complete.cases(df))</code></p>
</div>
</div>
<p>Instead we are going to use mean imputation here and replace all the missing values in each variable with the mean of that variable. If we wanted to do this for a single variable we could use the code below, I’m first going to create a copy of our data set called <code>dfImp</code> so we leave the original intact.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>dfImp <span class="ot">&lt;-</span> df</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dfImp<span class="sc">$</span>DRIVE[<span class="fu">is.na</span>(dfImp<span class="sc">$</span>DRIVE)] <span class="ot">&lt;-</span> <span class="fu">mean</span>(dfImp<span class="sc">$</span>DRIVE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This might look complex but if we break it down into individual steps we can understand.</p>
<p>On the right side of the assign operator (<code>&lt;-</code>) we have <code>mean(dfImp$DRIVE, na.rm = TRUE)</code>. The reason we can’t simply use <code>mean(dfImp)</code> is because if there are any <code>NA</code> values in that variable <code>mean()</code> will simply return a <code>NA</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>DRIVE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>Instead, using the code below tell the <code>mean()</code> function to ignore any missing values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>DRIVE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.31217</code></pre>
</div>
</div>
<p>So the right side of our code was calculating the mean (while ignoring missing values). What is the left side <code>dfImp$DRIVE[is.na(dfImp$DRIVE)]</code> doing? So if we simply run this on it’s own we can see it returns the two <code>NA</code> values in <code>df$DRIVE</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>DRIVE[<span class="fu">is.na</span>(df<span class="sc">$</span>DRIVE)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA NA</code></pre>
</div>
</div>
<p>When we combine these two parts, the code finds the <code>NA</code> values in <code>dfImp$Drive</code> and then overwrites them with the mean of that variable. This is mean imputation. We could do this one by one for each variable but that is generally not considered good practice in code to list out 20 lines of code.</p>
<p>Instead we can use a function called <code>lapply()</code> which applies the same function to a list of variables, if you give it a dataframe as an input it will apply the same function to each column. Don’t worry if this seems complex at the moment we will use functions like this more often as we progress through the course.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dfImp <span class="ot">&lt;-</span> df                                   <span class="co"># keep the raw data untouched</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dfImp)) <span class="co">#count the number of NAs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dfImp[] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(dfImp, <span class="cf">function</span>(x) {</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  x[<span class="fu">is.na</span>(x)] <span class="ot">&lt;-</span> <span class="fu">mean</span>(x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  x</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dfImp))    <span class="co">#count the number of NAs again</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Just as we did in the lab session with outliers it would also be good to label which rows of the <code>dfImp</code> data set we performed mean imputation on. This would later enable us to quickly include/exclude these cases from analysis if we wanted to check the effects of our process. We can do this using the follwing code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dfImp<span class="sc">$</span>imputed_row <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">complete.cases</span>(df)  </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(dfImp<span class="sc">$</span>imputed_row) <span class="co"># check that we have labelled the right rows with a TRUE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   9 186</code></pre>
</div>
</div>
<p>However, there is one potential problem in the way we have processed the data. Before we performed mean imputation, we did not first check for outliers.</p>
<p><strong>Why might this cause a problem?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>Extreme values in a variable can bias the mean in that direction. If we had a few large outliers our computed mean might not be an accurate reflection of the clean data and therefore out mean imputation would contain this bias. If using mean imputation make sure to screen for outliers first.</p>
</div>
</div>
</section>
<section id="section-c.-detecting-outliers-with-z-scores" class="level2">
<h2 class="anchored" data-anchor-id="section-c.-detecting-outliers-with-z-scores">SECTION C. DETECTING OUTLIERS WITH Z-SCORES</h2>
<p>We are going to do this the <code>df$Lack_of_PremediationUPPS</code> variable. Let’s first plot a histogram of the data to get an initial visualisation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dfImp<span class="sc">$</span>Lack_of_PremediationUPPS, <span class="at">breaks =</span> <span class="dv">20</span>, <span class="at">main =</span> <span class="st">"Histogram of Lack_of_PremediationUPPS"</span>, <span class="at">xlab =</span> <span class="st">"Lack_of_PremediationUPPS"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PS71020_Unit2_Homework_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It seems like we have at least one extreme value that is near 50, but it isn’t clear exactly how many data points are there. We could check this using a manual threshold and find out:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(dfImp<span class="sc">$</span>Lack_of_PremediationUPPS<span class="sc">&gt;</span><span class="dv">40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  96 114</code></pre>
</div>
</div>
<p>I’ve used the same <code>which()</code> function as earlier to ask <strong>R</strong> to return the positions of any values in <code>df$Lack_of_PremediationUPPS</code> that are <strong>greater than</strong> (the <strong>&gt;</strong> symbol) 40. The value of 40 was purely based of choosing a value in the histogram that separated the data.</p>
<p><strong>How many outliers do we have based on this criterion of <code>&gt;40</code>?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>Two, in rows of 96 and 114 of <code>df</code>.</p>
</div>
</div>
<p>However, manually defining values like this is not best practice unless there are clear theoretical grounds for choosing them (i.e.&nbsp;impossible/implausible values for Age, reaction time, or score on a scale).</p>
<p>Instead we can use <strong>z-scores</strong> as a way of <strong>standardising</strong> or <strong>scaling</strong> our data.</p>
<p>See <a href="./Pre_sessional_2.html#sec-reviewing-data">Section from Pre-sesional tutorial 3</a> for another example of calculating z-scores that explains how to do this step by step. Here we are going to use the function <code>scale()</code> that will do it for us in once go.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>PM_z <span class="ot">&lt;-</span> <span class="fu">scale</span>(dfImp<span class="sc">$</span>Lack_of_PremediationUPPS) <span class="co">#calculate z-scores for the Negative_UrgencyUPPS variable.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Taking a z-score means standardising (or scaling) the data so that it now has a mean of 0 and a standard deviation of 1. This makes it then easier to compare to other variables/data sets and to apply the same cut-off values for outliers to all variables.</p>
<p>We can check the mean and standard deviation of the new variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(PM_z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.681791e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(PM_z)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>We can see the mean is very close to 0 and the standard deviation is exactly 1.</p>
<p>See <a href="./Pre_sessional_2.html#sec-reviewing-data">Section from Pre-sesional tutorial 3</a> for an explanation of numbers in <strong>E notation</strong>. The number 1.681791e-16 means:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span>(<span class="fl">1.681791e-16</span>, <span class="at">scientific =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.0000000000000001681791"</code></pre>
</div>
</div>
<p>So is very very close to 0.</p>
<p>If we plot the histogram of our <code>PM_z</code> variable we can see that the general shape is very similar to before but the data is centered on the mean of 0 and each point is now expressed as the number of standard deviations it is away from that mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(PM_z, <span class="at">breaks =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PS71020_Unit2_Homework_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A common threshold to choose when using z-scores is less than -3.29 or greater than +3.29. (These are the z-scores associated with a <em>p</em>-value less than .001.)</p>
<p>If we wanted to do this for our <code>PM_z</code> variable we could use this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">abs</span>(PM_z) <span class="sc">&gt;</span> <span class="fl">3.29</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  96 114</code></pre>
</div>
</div>
<p>The <code>abs()</code> function makes all the numbers positive so values of -2 become +2, but values of +2 stay as +2. This means we can check for <code>&lt;-3.29</code> and <code>&gt;3.29</code> at the same time.</p>
<p>We can see that using this rule has returned the same rows (96 and 114) as we identified earlier.</p>
<p>We can use some slightly more advanced code to check all variables in one go and get <strong>R</strong> to return the names and positions of any outliers exceeding these limits.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a vector with the names of the variables we want to check</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Negative_UrgencyUPPS"</span>, <span class="st">"Lack_of_PremediationUPPS"</span>, <span class="st">"BAS"</span>, <span class="st">"FUN"</span>) </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co">#scale all of them at the same time and assign to a matrix z</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">scale</span>(dfImp[vars])</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">abs</span>(z) <span class="sc">&gt;</span> <span class="fl">3.29</span>, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     row col
[1,]  11   1
[2,]  15   1
[3,]  96   2
[4,] 114   2
[5,] 157   3
[6,] 157   4</code></pre>
</div>
</div>
<p><strong>Which rows of which variables are outliers according the to abs(z)&gt;3.29 rule?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>Rows 11 and 15 in Negative_UrgencyUPPS, rows 96 and 114 in Lack_of_PremediationUPPS, and row 157 in BAS and FUN.</p>
</div>
</div>
<p>One thing to keep in mind is that the z-score method assumes that the data is roughly normally distributed, in very skewed data it can pick up the tails of the distribution which might not be real outliers.</p>
</section>
<section id="sec-compound-plots" class="level2">
<h2 class="anchored" data-anchor-id="sec-compound-plots">SECTION D. COMPOUND PLOTS</h2>
<p>To visualise linearity, normality and homoscedasticity in a pair of variables is possible by creating separate plots. However, for doing this all in one plot we can use compound plots. These can be built using base <strong>R</strong> functions but some packages can make things much simpler.</p>
<p>See <a href="./PS71020_Unit1_Lab.html#sec-packages-rstudio">Section E from Lab 1</a> for some more information on packages.</p>
<p>In this case we are going to use a function called <code>ggscatterhist()</code> from a package called <strong>ggpubr</strong>. There are a lot of packages that start with <strong>gg</strong> and they are mainly extensions to a package called <strong>ggplot2</strong> which is the most widely used for plotting in R.</p>
<p>Before we can use the functions from this package we need to load it’s functions into <strong>R</strong>s memory:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
</div>
<p>You will also see that it loaded the package <strong>ggplot2</strong> because some of the functions in <strong>ggpubr</strong> require other functions in <strong>ggplot2</strong>, this is called dependency between packages. <strong>R</strong> should normally handle dependencies for you and load any required packages automatically.</p>
<p>The code below produces a scatter graph of <code>Positive_UrgencyUPPS</code> and <code>Sensation_SeekingUPPS</code>, and places the histograms in the margins.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggscatterhist</span>(dfImp, <span class="at">x =</span> <span class="st">"Positive_UrgencyUPPS"</span>, <span class="at">y =</span> <span class="st">"Sensation_SeekingUPPS"</span>,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">add =</span> <span class="st">"reg.line"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">conf.int =</span> <span class="cn">TRUE</span>,                                    </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">margin.params =</span> <span class="fu">list</span>(<span class="at">fill =</span> <span class="st">"lightgray"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PS71020_Unit2_Homework_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What code do you think you would need to produce the following plot?</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PS71020_Unit2_Homework_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p><code>ggscatterhist(dfImp, x = "BAS", y = "BIS",</code> <code>add = "reg.line",</code> <code>conf.int = TRUE,</code> <code>color = "cornflowerblue",</code> <code>margin.params = list(fill = "cornflowerblue"))</code></p>
</div>
</div>
<p><strong>Do you think these variables are normally distributed? Linearly related? Homoscedastic?</strong></p>
<div class="answer-box">
<p><input type="text" class="answer-input" placeholder="Type your answer here..."> <button class="reveal-btn" disabled="">Show answer</button></p>
<div class="answer">
<p>Normality: both show a mild negative skew. Linearity: The trend looks to be a straight line but there isn’t really a relationship. Homoscedasticity: The vertical spread of BIS, increases slightly as values of BAS increase. The spread is visually wider to the right hand side of the plot.</p>
</div>
</div>
<p>In this case none of these violations are severe enough to prevent us analysing the data but we should still report them all for reproducibility.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script src="answer-gate.js"></script>




</body></html>